version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - db-network

  dotnet-api:
    build:
      context: ./DotnetTasksApi
      dockerfile: Dockerfile
    environment:
      DOTNET_RUNNING_IN_CONTAINER: "true"
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8080:8080" # updated port
    depends_on:
      - psql-database
    networks:
      - db-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - db-network

  # PostgreSQL Database
  psql-database:
    container_name: psql-database
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dailytasks
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - db-network

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - db-network

  # pgAdmin (Web UI for PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: rsteam@ketchup.com
      PGADMIN_DEFAULT_PASSWORD: rsteam
    ports:
      - "5050:80"
    volumes:
      - pgadmin-config:/var/lib/pgadmin
    depends_on:
      - psql-database
    networks:
      - db-network

  # Bun Elysia App
  bun-elysia:
    build:
      context: ./bun-elysia
    environment:
      PORT: 6485
      PSQL_HOST: psql-database
      PSQL_DB: dailytasks
      PSQL_USER: postgres
      PSQL_PASSWORD: root
      PSQL_PORT: 5432
    ports:
      - "6485:6485"
    depends_on:
      - psql-database
    networks:
      - db-network

  # Bun Hono App
  bun-hono:
    build:
      context: ./bun-hono
    environment:
      PORT: 1103
      PSQL_HOST: psql-database
      PSQL_DB: dailytasks
      PSQL_USER: postgres
      PSQL_PASSWORD: root
      PSQL_PORT: 5432
    ports:
      - "1103:1103"
    depends_on:
      - psql-database
    networks:
      - db-network

  # Node Express App
  node-express:
    build:
      context: ./node-express
    environment:
      PORT: 6582
      PSQL_HOST: psql-database
      PSQL_DB: dailytasks
      PSQL_USER: postgres
      PSQL_PASSWORD: root
      PSQL_PORT: 5432
    ports:
      - "6582:6582"
    depends_on:
      - psql-database
    networks:
      - db-network

  # Node Fastify App
  node-fastify:
    build:
      context: ./node-fastify
    environment:
      PORT: 3000
      PSQL_HOST: psql-database
      PSQL_DB: dailytasks
      PSQL_USER: postgres
      PSQL_PASSWORD: root
      PSQL_PORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - psql-database
    networks:
      - db-network

volumes:
  pgdata:
  pgadmin-config:
  grafana-data:

networks:
  db-network:
    driver: bridge
