global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "node-express"
    static_configs:
      - targets: ["node-express:6582"]

  - job_name: "node-fastify"
    static_configs:
      - targets: ["node-fastify:3000"]

  - job_name: "bun-elysia"
    static_configs:
      - targets: ["bun-elysia:6485"]

  - job_name: "bun-hono"
    static_configs:
      - targets: ["bun-hono:1103"]

  - job_name: "dotnet"
    static_configs:
      - targets: ["dotnet:5001"]
