global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "dotnet-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["dotnet-api:8080"]

  - job_name: "node-express"
    metrics_path: /metrics
    static_configs:
      - targets: ["node-express:6582"]

  - job_name: "node-fastify"
    metrics_path: /metrics
    static_configs:
      - targets: ["node-fastify:3000"]

  - job_name: "bun-elysia"
    metrics_path: /metrics
    static_configs:
      - targets: ["bun-elysia:6485"]

  - job_name: "bun-hono"
    metrics_path: /metrics
    static_configs:
      - targets: ["bun-hono:1103"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
